stages:
  - build
  - deploy

build:
  stage: build
  script:
    - gradle build --info
  tags:
    - java
    - gradle

deploy:
  stage: deploy
  script:
    - gradle publish
  tags:
    - java
    - gradle
  only:
    - tags